### ISSUE TITLE
2.9.0.3 errors

### ISSUE THREAD

**Issue by skream27** [KoalaBear84/OpenDirectoryDownloader#133]
![Screenshot_2](https://user-images.githubusercontent.com/42325544/227166877-cc171658-b0e9-474f-b733-7c49a2a0e6db.png)
I think you broke the program, dear koala :D

**Comment by KoalaBear84** [comment]
Haha. Yes, I guess so. It was indeed not tested.

Thanks for letting me know.

I had to commit it because I already committed some other code which broke the build.

Now I've broke the browser part 😂😅

In the meantime take the previous version. I'll try to fix it tomorrow.

**Comment by KoalaBear84** [comment]
Well, that 'tomorrow' failed, as the usual. But it seems this is another error.. That they don't support this feature on the single-file bundle. Quickly I only saw the familiar "Object refence not set to an instance of an object", but that wasn't the main issue.

I'll have to take a look at this later..

**Comment by skream27** [comment]
previous version is working with no problem, don't worry we are waiting.

**Comment by KoalaBear84** [comment]
Finally took some time to look into it, looks like it's already fixed in the library, but not yet released. Will wait until it is released and will build a new version.

https://github.com/hardkoded/puppeteer-sharp/issues/2124

Also need to look into another issue, at least related to the browser part, and that it only starts a maximum of one at a time. I almost had to reboot my computer because it was starting 10 Chromiums a second and I could retake control 😅
