### ISSUE TITLE
Support for Mediafire

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#45]
Do i have to fill out the template for this one? :wink:

**Comment by KoalaBear84** [comment]
Haha. I also added it this morning, not coincidentally as it was posted on Reddit.

But.. I do have many others as well like Amazon Drive, Dropbox, Bucket, Box.com, SugarSync etc. :)

**Comment by MCOfficer** [comment]
Yeah, no pressure. Just adding some information:

API Docs: https://www.mediafire.com/developers/core_api/1.5/getting_started/

They don't link it on the developer portal, but there appears to be an SDK? Might be outdated as hell though. https://www.nuget.org/packages/MediaFireSDK/ , https://github.com/MediaFire/mediafire-csharp-open-sdk

**Comment by KoalaBear84** [comment]
Supported in https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.3.0.6

**Comment by KoalaBear84** [comment]
Ohh, forgot one thing. Need a testfolder with 100+ files to implement paging support.

**Comment by Chaphasilor** [comment]
> Ohh, forgot one thing. Need a testfolder with 100+ files to implement paging support.

How does this relate to #9?

**Comment by KoalaBear84** [comment]
Good question. Not sure. Most of the specific parsers have built in paging support, because it is very specific.

Not sure what I wanted in #9, or how that can be implemented easily. Maybe for some things it can, like when there is a generic element on the page to go to the next page or so. We don't have many examples of this, if so, it was already implemented by now. So there is not a great need for it. And it seems like the only example I had was gone before I could implement it 😅

**Comment by KoalaBear84** [comment]
Still need that example for Mediafire though, although it might also be very specific. Not sure how I implemented the indexing.

**Comment by KoalaBear84** [comment]
Made my own example.

Version is currently building.
